# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/james604s"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/shao-hung-tseng-106455134/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "medium"
name = "Medium"
url = "https://medium.com/sq-catch-and-note"

[social.params]
icon = "brand-medium"

[[social]]
identifier = "email"
name = "Email"
url = "leonardtsengbc@gmail.com"

[social.params]
icon = "brand-email"